from __future__ import annotations

import saealib.core.contracts.kinds
from saealib.core.contracts.assumptions import (
    ASSUMPTION_KEYS,
    AssumptionDescriptor,
    AssumptionSet,
    register_assumption,
    validate_assumption_name,
)
from saealib.core.contracts.contract import ComponentContract, PartSpec
from saealib.core.contracts.data import (
    DATA_SPEC_KINDS,
    Contained,
    DataSpec,
    DataSpecKind,
    Fixed,
    Product,
    SchemaBinding,
    Var,
    data_spec_kind,
    is_data_spec_compatible,
    is_set_like,
    register_data_spec,
)
from saealib.core.contracts.execution import (
    RUNTIME_CAPABILITIES,
    ExecutionContract,
    RuntimeCapability,
)
from saealib.core.contracts.lifecycle import (
    EVENT_VOCABULARY,
    EventSubscription,
    LifecycleContract,
)
from saealib.core.contracts.ports import (
    CARDINALITIES,
    MANY,
    ONE,
    OPTIONAL,
    SERVICE_VOCABULARY,
    Cardinality,
    PortCompatibility,
    PortContract,
    PortDirection,
    PortSpec,
    ServiceRequirement,
    cardinality_satisfies,
    check_port_compatibility,
    validate_port_contract_directions,
)
from saealib.core.contracts.roles import ROLES, RoleName
from saealib.core.contracts.schema import (
    SCHEMA_CONFLICT_REASONS,
    SCHEMA_VARIABLES,
    SchemaConstraint,
    Substitution,
    UnificationResult,
    unify_bindings,
    unify_data_specs,
)
from saealib.core.contracts.state import StateContract
from saealib.core.contracts.vocabulary import (
    Vocabulary,
    VocabularyDescriptor,
    is_valid_name,
    validate_identifier,
    validate_name,
)

__all__ = [
    "ASSUMPTION_KEYS",
    "CARDINALITIES",
    "DATA_SPEC_KINDS",
    "EVENT_VOCABULARY",
    "MANY",
    "ONE",
    "OPTIONAL",
    "ROLES",
    "RUNTIME_CAPABILITIES",
    "SCHEMA_CONFLICT_REASONS",
    "SCHEMA_VARIABLES",
    "SERVICE_VOCABULARY",
    "AssumptionDescriptor",
    "AssumptionSet",
    "Cardinality",
    "ComponentContract",
    "Contained",
    "DataSpec",
    "DataSpecKind",
    "EventSubscription",
    "ExecutionContract",
    "Fixed",
    "LifecycleContract",
    "PartSpec",
    "PortCompatibility",
    "PortContract",
    "PortDirection",
    "PortSpec",
    "Product",
    "RoleName",
    "RuntimeCapability",
    "SchemaBinding",
    "SchemaConstraint",
    "ServiceRequirement",
    "StateContract",
    "Substitution",
    "UnificationResult",
    "Var",
    "Vocabulary",
    "VocabularyDescriptor",
    "cardinality_satisfies",
    "check_port_compatibility",
    "data_spec_kind",
    "is_data_spec_compatible",
    "is_set_like",
    "is_valid_name",
    "register_assumption",
    "register_data_spec",
    "unify_bindings",
    "unify_data_specs",
    "validate_assumption_name",
    "validate_identifier",
    "validate_name",
    "validate_port_contract_directions",
]
