from saealib.surrogate.accuracy import (
    RMSE,
    AccuracyEvaluator,
    HeldOutAccuracyEvaluator,
    KFoldAccuracyEvaluator,
    LOOAccuracyEvaluator,
    R2Score,
    SpearmanCorrelation,
    SurrogateAccuracy,
    SurrogateAccuracyMetric,
)
from saealib.surrogate.base import ComparisonSurrogate, RegressionSurrogate, Surrogate
from saealib.surrogate.manager import (
    CompositeSurrogateManager,
    GlobalSurrogateManager,
    LocalSurrogateManager,
    PairwiseSurrogateManager,
    SurrogateManager,
    product_combine,
    rank_weighted_combine,
)
from saealib.surrogate.per_objective import PerObjectiveSurrogate
from saealib.surrogate.prediction import PredictionChannel, SurrogatePrediction
from saealib.surrogate.rbf import RBFSurrogate
from saealib.surrogate.rbf_kernels import (
    CubicKernel,
    GaussianKernel,
    LinearKernel,
    MaternKernel,
    MultiquadricKernel,
    RBFKernel,
    ThinPlateSplineKernel,
)
from saealib.surrogate.sklearn_surrogate import (
    SklearnClassificationSurrogate,
    SklearnGPRSurrogate,
    SklearnLGBMSurrogate,
    SklearnNNSurrogate,
    SklearnRFCClassificationSurrogate,
    SklearnRFRSurrogate,
    SklearnSurrogate,
    SklearnSVCClassificationSurrogate,
    SklearnSVMSurrogate,
    SklearnXGBSurrogate,
)
from saealib.surrogate.switching import (
    AccuracyBasedSurrogateSwitcher,
    GenCtrlSwitcher,
    ManagerSwitcher,
    StrategySwitcher,
)
from saealib.surrogate.torch_surrogate import TorchSurrogate
from saealib.surrogate.training_set import (
    ArchiveObjectiveSet,
    ConstraintObjectiveSet,
    FeasibilityClassificationSet,
    KNNConstraintObjectiveSet,
    KNNObjectiveSet,
    LevelBasedSet,
    PairwiseComparisonSet,
    ReferencePointComparisonSet,
    TopKBipartitionSet,
    TrainingData,
    TrainingSet,
)

__all__ = [
    "RMSE",
    "AccuracyBasedSurrogateSwitcher",
    "AccuracyEvaluator",
    "ArchiveObjectiveSet",
    "ComparisonSurrogate",
    "CompositeSurrogateManager",
    "ConstraintObjectiveSet",
    "CubicKernel",
    "FeasibilityClassificationSet",
    "GaussianKernel",
    "GenCtrlSwitcher",
    "GlobalSurrogateManager",
    "HeldOutAccuracyEvaluator",
    "KFoldAccuracyEvaluator",
    "KNNConstraintObjectiveSet",
    "KNNObjectiveSet",
    "LOOAccuracyEvaluator",
    "LevelBasedSet",
    "LinearKernel",
    "LocalSurrogateManager",
    "ManagerSwitcher",
    "MaternKernel",
    "MultiquadricKernel",
    "PairwiseComparisonSet",
    "PairwiseSurrogateManager",
    "PerObjectiveSurrogate",
    "PredictionChannel",
    "R2Score",
    "RBFKernel",
    "RBFSurrogate",
    "ReferencePointComparisonSet",
    "RegressionSurrogate",
    "SklearnClassificationSurrogate",
    "SklearnGPRSurrogate",
    "SklearnLGBMSurrogate",
    "SklearnNNSurrogate",
    "SklearnRFCClassificationSurrogate",
    "SklearnRFRSurrogate",
    "SklearnSVCClassificationSurrogate",
    "SklearnSVMSurrogate",
    "SklearnSurrogate",
    "SklearnXGBSurrogate",
    "SpearmanCorrelation",
    "StrategySwitcher",
    "Surrogate",
    "SurrogateAccuracy",
    "SurrogateAccuracyMetric",
    "SurrogateManager",
    "SurrogatePrediction",
    "ThinPlateSplineKernel",
    "TopKBipartitionSet",
    "TorchSurrogate",
    "TrainingData",
    "TrainingSet",
    "product_combine",
    "rank_weighted_combine",
]
