import os
import sys
from importlib.metadata import version as _get_version

sys.path.insert(0, os.path.abspath("../src"))

# -- Project information -----------------------------------------------------
project = "saealib"
copyright = "2026, shlka"
author = "shlka"
release = _get_version("saealib")
myst_substitutions = {"version": release}

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_proof",
    "sphinxcontrib.mermaid",
    "sphinxcontrib.bibtex",
    "sphinx_sitemap",
    "sphinx_multiversion",
]

# -- sphinxcontrib-mermaid ---------------------------------------------------
mermaid_init_js = """
mermaid.initialize({
    startOnLoad: true,
    flowchart: {
        useMaxWidth: false,
        htmlLabels: true,
        nodeSpacing: 50,
        rankSpacing: 75,
        diagramPadding: 20,
        subgraphPadding: 30
    }
});
"""


templates_path = ["_templates"]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "**/_page_template.md",
]

# -- MyST-Parser -------------------------------------------------------------
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "substitution",
    "tasklist",
]

# -- sphinxcontrib-bibtex ------------------------------------------------------
bibtex_bibfiles = ["references.bib"]
bibtex_default_style = "unsrt"

# -- Internationalization -----------------------------------------------------
language = "en"
locale_dirs = ["locale/"]
gettext_compact = False

# -- HTML output -------------------------------------------------------------
html_baseurl = "https://shlka.github.io/saealib/"
sitemap_url_scheme = "{link}"
html_theme = "pydata_sphinx_theme"
html_static_path = ["_static"]
html_extra_path = ["googleb2b2a6492b1c5bc1.html"]
html_css_files = ["css/custom.css"]
html_js_files = ["js/lang-switch.js", "js/sidebar-dialog-fix.js", "js/mermaid-scale.js"]

html_theme_options = {
    "logo": {
        "image_light": "logo-light.svg",
        "image_dark": "logo-dark.svg",
        "alt_text": "saealib",
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/shlka/saealib",
            "icon": "fa-brands fa-square-github",
            "type": "fontawesome",
        },
    ],
    # "search-button-field" stays in navbar_persistent (desktop header +
    # always-visible `.navbar-persistent--mobile`, per sections/header.html)
    # since it's used often enough to warrant zero-tap access even on
    # mobile. "search-button-field" must be re-listed explicitly here —
    # setting navbar_persistent ourselves overrides the theme's own
    # default-if-unset logic.
    "navbar_persistent": ["search-button-field"],
    # version-switcher/lang-switcher go in navbar_end instead: on desktop
    # they render in `.navbar-header-items__end` same as before, but below
    # the 960px breakpoint (where `.navbar-header-items` itself collapses to
    # display:none) sections/sidebar-primary.html renders navbar_end items a
    # second time inside `.sidebar-header-items__end`, i.e. behind the
    # hamburger ("primary-toggle") drawer rather than always-on — trading
    # one tap for a less cluttered mobile header.
    # theme-switcher/navbar-icon-links must be re-listed explicitly here too
    # (same reason as navbar_persistent above) — otherwise setting
    # navbar_end at all drops the theme's own defaults for them, which is
    # why the light/dark toggle and the GitHub icon (icon_links) disappeared.
    "navbar_end": ["version-switcher", "lang-switcher", "theme-switcher", "navbar-icon-links"],
    "switcher": {
        "json_url": html_baseurl.rstrip("/") + "/versions.json",
        # Placeholder; overwritten per-build by _set_version_switcher_match()
        # below via the config-inited hook.
        "version_match": "dev",
    },
    # versions.json is generated by docs.yml *after* the Sphinx build step
    # that reads this option, so validating it here (network fetch or local
    # read) would always fail on a fresh build and turn into a hard failure
    # under the `-W` strict build.
    "check_switcher": False,
}
html_favicon = "_static/icon.svg"

# -- autodoc -----------------------------------------------------------------
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
}
napoleon_numpy_docstring = True
napoleon_google_docstring = False

# -- autosummary -------------------------------------------------------------
autosummary_generate = True
autosummary_imported_members = False

# -- warnings ----------------------------------------------------------------
suppress_warnings = ["toc.no_title"]

# -- sphinx-multiversion -------------------------------------------------------
# Only final releases (no pre-release suffix, e.g. v0.1.0) get a permanent,
# frozen snapshot directory. Pre-release tags (v0.1.0b1, ...) intentionally do
# not match, so they don't accumulate one directory each; they are covered by
# the rolling "dev/" build performed as a separate sphinx-build step in
# docs.yml instead. See CONTRIBUTING.md "Release Process" for the full policy.
smv_tag_whitelist = r"^v\d+\.\d+\.\d+$"
smv_branch_whitelist = r"^$"
smv_remote_whitelist = None
smv_outputdir_format = "{ref.name}"
smv_prefer_remote_refs = False


# -- Dynamic version-switcher match -------------------------------------------
# sphinx-multiversion injects `-D smv_current_version=<tag>` when building a
# frozen per-tag snapshot; the rolling "dev" snapshot in docs.yml is built
# with a plain `sphinx-build`, where `smv_current_version` stays at its
# registered default of "". Map both cases onto the "version" values used in
# versions.json so the switcher highlights/selects the right entry.
def _set_version_switcher_match(app, config):
    switcher = config.html_theme_options.get("switcher")
    if isinstance(switcher, dict):
        switcher["version_match"] = config.smv_current_version or "dev"


def setup(app):
    app.connect("config-inited", _set_version_switcher_match)
